FROM ubuntu:focal-20200925

# Terraform version parameter.
ARG tf_version="1.5.4"
# Go version parameter.
ARG golang_version="1.20.6"
# This parameter include avi_version e.g 30.2.1
ARG avi_version="30.2.1"
# Branch name to build on specific branch
ARG branch=${avi_version}

# Set up env variables for Go and Terraform
ENV GOROOT "/usr/local/go"
ENV GOPATH $HOME
ENV GOBIN "$HOME/bin"
ENV PATH "$PATH:/usr/local/go/bin:$HOME/bin:/avi/scripts"
ENV TF_PLUGIN_CACHE_DIR "$HOME/.terraform.d/plugin-cache"

# Install basic packages and clone alb-sdk
RUN apt-get update && \
    apt install -y software-properties-common && \
    apt update && \
    apt install -y python3.8 \
    python-is-python3 \
    python3.8-dev \
    python3.8-distutils \
    wget \
    git \
    curl && \
    cd /tmp && curl -O https://bootstrap.pypa.io/get-pip.py && \
    python3.8 /tmp/get-pip.py && \
    rm -rf /usr/local/bin/pip && \
    git clone https://github.com/vmware/alb-sdk /alb-sdk

# Checkout to branch 
WORKDIR /alb-sdk
RUN git checkout ${branch}

# This will install tar bundle for avisdk and migrationtools.
WORKDIR /alb-sdk/python/
RUN bash create_sdk_pip_packages.sh sdk
# Install migrationtools bundle
RUN bash create_sdk_pip_packages.sh migrationtools

# Install required packages
WORKDIR /
RUN apt-get update && \ 
    apt-get install -y \
    apache2-utils \
    apt-transport-https \
    lsb-release \
    gnupg \
    dnsutils \
    httpie \
    inetutils-ping \
    iproute2 \
    libffi-dev \
    libssl-dev \
    lua5.3 \
    make \
    netcat \
    nmap \
    slowhttptest \
    sshpass \
    tree \
    unzip \
    jq \
    gcc \
    vim && \
    pip3 install setuptools==57.5.0 && \
    pip3 uninstall ansible-core -y \
    pip3 install ansible==2.9.13 && \
    pip3 install ansible-lint \
    bigsuds \
    f5-sdk \
    flask \
    jinja2 \
    jsondiff \
    networkx \
    openpyxl \
    openstacksdk \
    netaddr \
    pandas \
    paramiko \
    pexpect \
    pycrypto \
    pyOpenssl \
    pyparsing \
    pytest \
    pyvmomi \
    pyyaml \
    requests-toolbelt \
    xlsxwriter \
    urllib3 \
    hvac \
    ansible_runner \
    vcrpy \
    parameterized \
    /alb-sdk/python/dist/avisdk-${avi_version}.tar.gz \
    /alb-sdk/python/dist/avimigrationtools-${avi_version}.tar.gz


# This script will install nsx dependencies.
WORKDIR /alb-sdk/python/avi/migrationtools/nsxt_converter/
RUN python3 install_nsx_dependencies.py

# Install terraform
WORKDIR /
RUN curl https://releases.hashicorp.com/terraform/${tf_version}/terraform_${tf_version}_linux_amd64.zip -o terraform_${tf_version}_linux_amd64.zip &&  \
    unzip terraform_${tf_version}_linux_amd64.zip -d /usr/local/bin && \
    rm -rf terraform_${tf_version}_linux_amd64.zip

# Clone avitools and devops repositories
RUN cd $HOME && \
    git clone https://github.com/avinetworks/devops && \
    git clone https://github.com/vmware/nsx-advanced-load-balancer-tools avitools && \
    mkdir -p /avi/scripts && \
    cp -r avitools/scripts/* /avi/scripts && \
    rm -rf $HOME/avitools

# Install go for AVI terraform provider
RUN curl -L https://go.dev/dl/go${golang_version}.linux-amd64.tar.gz -o go${golang_version}.linux-amd64.tar.gz && \
    rm -rf /usr/local/go && tar -C /usr/local -xzf go${golang_version}.linux-amd64.tar.gz && \
    go version && \
    rm go${golang_version}.linux-amd64.tar.gz

# Clone terraform provider repository and build provider locally.
RUN cd $HOME && \
    git clone https://github.com/vmware/terraform-provider-avi && \
    cd ~/terraform-provider-avi && \
    git checkout ${branch} && \
    make fmt . && \
    go mod tidy && \
    make build13 && \
    mkdir -p $HOME/.terraform.d/ && \
    mkdir -p $HOME/.terraform.d/plugin-cache && \
    cd ~/terraform-provider-avi/examples/aws/cluster_stages/1_aws_resources && \
    terraform init

# Clone ansible repo and install ansible collections.
RUN cd $HOME && \
    git clone https://github.com/vmware/ansible-collection-alb && \
    cd ~/ansible-collection-alb && \
    git checkout ${branch} && \
    ansible-galaxy collection build && \
    ansible-galaxy collection install vmware-alb-*.tar.gz && \
    pip3 install -r ~/.ansible/collections/ansible_collections/vmware/alb/requirements.txt

# Verify all converters files.
RUN touch list && \
    echo '#!/bin/bash' > avitools-list && \
    echo "echo "f5_converter.py"" >> avitools-list && \
    echo "echo "netscaler_converter.py"" >> avitools-list && \
    echo "echo "gss_convertor.py"" >> avitools-list && \
    echo "echo "f5_discovery.py"" >> avitools-list && \
    echo "echo "avi_config_to_ansible.py"" >> avitools-list && \
    echo "echo "ace_converter.py"" >> avitools-list && \
    echo "echo "virtualservice_examples_api.py"" >> avitools-list && \
    echo "echo "config_patch.py"" >> avitools-list && \
    echo "echo "vs_filter.py"" >> avitools-list && \
    echo "echo "nsxt_converter.py"" >> avitools-list

# Verify all script in avitools-list
RUN for script in $(ls /avi/scripts); do echo "echo $script" >> avitools-list; done;

# make executables
RUN chmod +x avitools-list && \
    cp avitools-list /usr/local/bin/ && \
    echo "alias avitools-list=/usr/local/bin/avitools-list" >> ~/.bashrc

# Clean out the cache
RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* $HOME/.cache $HOME/go/src $HOME/src

