#!/bin/bash -xe
echo $IMAGE_NAME

if [ $IMAGE_NAME ]; then
    AVI_VERSION="$(echo $IMAGE_NAME | cut -d ":"  -f2)"
    AVI_SDK_VERSION="$(echo $IMAGE_NAME | cut -d ":"  -f2)"
else
    AVI_VERSION=18.1.3
    AVI_SDK_VERSION=18.1.3
fi

docker build \
        --build-arg "avi_sdk_version=$AVI_SDK_VERSION" \
        --build-arg "avi_version=$AVI_VERSION" \
        -t $IMAGE_NAME .